# Generated by Django 3.2.4 on 2021-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='name',
        ),
        migrations.AddField(
            model_name='website',
            name='img',
            field=models.ImageField(default=2020, upload_to='qr_codes'),
            preserve_default=False,
        ),
    ]
