# Generated by Django 3.2.4 on 2021-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_auto_20210616_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default=2020, max_length=200),
            preserve_default=False,
        ),
    ]
